INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Austria','Europa'),
  ('Andorra','Europa'),
  ('Lituania','Europa'),
  ('Grecia','Europa'),
  ('Andorra','Europa'),
  ('Rusia','Europa'),
  ('Albania','Europa'),
  ('España','Europa'),
  ('Rusia','Europa'),
  ('Holanda','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Alemania','Europa'),
  ('Bielorusia','Europa'),
  ('Rumania','Europa'),
  ('Albania','Europa'),
  ('Islandia','Europa'),
  ('Malta','Europa'),
  ('Rumania','Europa'),
  ('Montenegro','Europa'),
  ('Holanda','Europa'),
  ('Bosnia','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Serbia','Europa'),
  ('Irlanda','Europa'),
  ('Bretaña','Europa'),
  ('Polonia','Europa'),
  ('Rumania','Europa'),
  ('Bosnia','Europa'),
  ('Hungría','Europa'),
  ('Montenegro','Europa'),
  ('Italia','Europa'),
  ('Noruega','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Luxemburgo','Europa'),
  ('Letonia','Europa'),
  ('Grecia','Europa'),
  ('Hungría','Europa'),
  ('Checo','Europa'),
  ('Bulgaria','Europa'),
  ('Francia','Europa'),
  ('Rumania','Europa'),
  ('Bretaña','Europa'),
  ('Estonia','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Serbia','Europa'),
  ('Suecia','Europa'),
  ('Chipre','Europa'),
  ('Serbia','Europa'),
  ('Bielorusia','Europa'),
  ('Montenegro','Europa'),
  ('Montenegro','Europa'),
  ('Rumania','Europa'),
  ('Bielorusia','Europa'),
  ('Macedonia','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Ucrania','Europa'),
  ('Malta','Europa'),
  ('Rusia','Europa'),
  ('Austria','Europa'),
  ('Estonia','Europa'),
  ('Islandia','Europa'),
  ('y','Europa'),
  ('Lituania','Europa'),
  ('Bosnia','Europa'),
  ('Bélgica','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Holanda','Europa'),
  ('Andorra','Europa'),
  ('Alemania','Europa'),
  ('Uzbekistán','Europa'),
  ('Moldavia','Europa'),
  ('Rusia','Europa'),
  ('Bielorusia','Europa'),
  ('Serbia','Europa'),
  ('Austria','Europa'),
  ('Malta','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Ucrania','Europa'),
  ('Bosnia','Europa'),
  ('Alemania','Europa'),
  ('Herzegovina','Europa'),
  ('Macedonia','Europa'),
  ('Andorra','Europa'),
  ('Albania','Europa'),
  ('Croacia','Europa'),
  ('Mónaco','Europa'),
  ('San_Marino','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Austria','Europa'),
  ('Gran','Europa'),
  ('Finlandia','Europa'),
  ('Lituania','Europa'),
  ('y','Europa'),
  ('Ucrania','Europa'),
  ('Ucrania','Europa'),
  ('Dinamarca','Europa'),
  ('Croacia','Europa'),
  ('Liechtenstein','Europa');
INSERT INTO PAIS (NOMBREPAIS,CONTINENTE)
VALUES
  ('Bielorusia','Europa'),
  ('Bulgaria','Europa'),
  ('Noruega','Europa'),
  ('Moldavia','Europa'),
  ('Uzbekistán','Europa'),
  ('Bulgaria','Europa'),
  ('Moldavia','Europa'),
  ('Lituania','Europa'),
  ('Bretaña','Europa'),
  ('Noruega','Europa');
